export { default as HomePage } from './HomePage.vue'
export { default as ContactPage } from './ContactPage.vue'
export { default as ProjectsPage } from './ProjectsPage.vue'
export { default as SkillsPage } from './SkillsPage.vue'
export { default as ExperiencePage } from './ExperiencePage.vue'
export { default as AchievementsPage } from './AchievementsPage.vue'
