// Brands skills
export { default as JavascriptLogo } from './icons/brands/JavascriptLogo.vue'
export { default as ReactLogo } from './icons/brands/ReactLogo.vue'
export { default as TailwindLogo } from './icons/brands/TailwindLogo.vue'
export { default as TypescriptLogo } from './icons/brands/TypescriptLogo.vue'
export { default as VueLogo } from './icons/brands/VueLogo.vue'
export { default as AngularLogo } from './icons/brands/AngularLogo.vue'
export { default as JiraLogo } from './icons/brands/JiraLogo.vue'
export { default as BitBucketLogo } from './icons/brands/BitBucketLogo.vue'
export { default as PiniaLogo } from './icons/brands/PiniaLogo.vue'
export { default as GitLogo } from './icons/brands/GitLogo.vue'
export { default as FigmaLogo } from './icons/brands/FigmaLogo.vue'
export { default as IllustratorLogo } from './icons/brands/IllustratorLogo.vue'
export { default as PhotoshopLogo } from './icons/brands/PhotoshopLogo.vue'
export { default as SassLogo } from './icons/brands/SassLogo.vue'

// Icons UI
export { default as IconArrow } from './icons/ui/IconArrow.vue'
export { default as IconDark } from './icons/ui/IconDark.vue'
export { default as IconGithub } from './icons/ui/IconGithub.vue'
export { default as IconGrandientFooter } from './icons/ui/IconGrandientFooter.vue'
export { default as IconHero } from './icons/ui/IconHero.vue'
export { default as IconLight } from './icons/ui/IconLight.vue'
export { default as IconLogo } from './icons/ui/IconLogo.vue'
export { default as IconMenu } from './icons/ui/IconMenu.vue'
export { default as IconProfile } from './icons/ui/IconProfile.vue'
export { default as IconLinkedin } from './icons/ui/IconLinkedin.vue'
